name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '.vscode/**', 'site/**']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', '.vscode/**', 'site/**']
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.4'

    - name: Get tag and set version on release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        sed "s|version = \"v.*\"|version = \"$GITHUB_REF_NAME\"|" -i version.go
        cat -n version.go

    - name: Set VERSION, EXE, and ZIP env vars
      run: |
        VERSION="$GITHUB_REF_NAME"
        if [[ $GITHUB_REF != "refs/tags/v"* ]]; then
          VERSION="${GITHUB_SHA::7}"
        fi
        {
          echo "VERSION=$VERSION"
          echo "EXE=zsv-playground-$VERSION-linux-amd64"
          echo "ZIP=$EXE.zip"
        } | tee -a "$GITHUB_ENV"

    - name: Build (linux/amd64)
      run: |
        GOOS=linux GOARCH=amd64 go build -v -x -ldflags '-w -s' -o "$EXE"
        zip "$ZIP" "$EXE"

    - name: Upload build artifact [${{ env.ZIP }}]
      uses: actions/upload-artifact@v4
      with:
        name: '${{ env.ZIP }}'
        path: '${{ env.ZIP }}'
        if-no-files-found: error

    - name: Upload with release [${{ env.ZIP }}]
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: '${{ env.ZIP }}'

    - name: Bump version on release [${{ env.VERSION }}]
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions@github.com'
        git fetch
        git checkout main
        git add version.go
        if [[ $(git diff) != "" ]]; then
          git commit -m "[CI] Bump version to $VERSION"
          git push -u origin main
        fi
