name: ci

on:
  push:
    branches: [main]
    paths-ignore:
    - "**.md"
    - ".vscode"
    - "site"
  pull_request:
    branches: [main]
    paths-ignore:
    - "**.md"
    - ".vscode"
    - "site"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      run: go build -v ./...
