name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '.vscode/**', 'site/**']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', '.vscode/**', 'site/**']
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.4'

    - name: Get tag and set version on release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        sed "s|version = \"v.*\"|version = \"$GITHUB_REF_NAME\"|" -i version.go
        cat -n version.go

    - name: Set VERSION, EXE, and ZIP env vars
      run: |
        VERSION="$GITHUB_REF_NAME"
        if [[ $GITHUB_REF != "refs/tags/v"* ]]; then
          VERSION="${GITHUB_SHA::7}"
        fi
        echo "VERSION=$VERSION" | tee -a "$GITHUB_ENV"

    - name: Build
      run: |
        for OS in linux, windows, darwin, freebsd; do
          EXE="zsv-playground-$VERSION-amd64-$OS"
          GOOS=linux GOARCH=amd64 go build -v -x -ldflags '-w -s' -o "$EXE"
          zip "$ZIP" "$EXE"
          echo "$(echo $OS | tr [:lower:] [:upper:])_ZIP=" | tee -a "$GITHUB_ENV"
        done
        ls -hl *.zip

    - name: Upload [${{ env.LINUX_ZIP }}]
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.LINUX_ZIP }}
        path: ${{ env.LINUX_ZIP }}
        if-no-files-found: error

    - name: Upload ${{ env.WINDOWS_ZIP }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.WINDOWS_ZIP }}
        path: ${{ env.WINDOWS_ZIP }}
        if-no-files-found: error

    - name: Upload ${{ env.DARWIN_ZIP }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DARWIN_ZIP }}
        path: ${{ env.DARWIN_ZIP }}
        if-no-files-found: error

    - name: Upload ${{ env.FREEBSD_ZIP }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FREEBSD_ZIP }}
        path: ${{ env.FREEBSD_ZIP }}
        if-no-files-found: error

    - name: Upload with release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          ${{ env.LINUX_ZIP }}
          ${{ env.WINDOWS_ZIP }}
          ${{ env.DARWIN_ZIP }}
          ${{ env.FREEBSD_ZIP }}

    - name: Bump version on release [${{ env.VERSION }}]
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions@github.com'
        git fetch
        git checkout main
        git add version.go
        if [[ $(git diff) != "" ]]; then
          git commit -m "[CI] Bump version to $VERSION"
          git push -u origin main
        fi
